/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_unown_tap_jni_NativeTAP */

#ifndef _Included_com_unown_tap_jni_NativeTAP
#define _Included_com_unown_tap_jni_NativeTAP
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_unown_tap_jni_NativeTAP_MarketData */

#ifndef _Included_com_unown_tap_jni_NativeTAP_MarketData
#define _Included_com_unown_tap_jni_NativeTAP_MarketData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_unown_tap_jni_NativeTAP_MarketData
 * Method:    register
 * Signature: (Lcom/unown/tap/jni/NativeCallback;Lcom/unown/tap/jni/NativeTAP/MarketData/Configuration;)V
 */
JNIEXPORT void JNICALL Java_com_unown_tap_jni_NativeTAP_00024MarketData_register
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_unown_tap_jni_NativeTAP_MarketData
 * Method:    deregister
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_unown_tap_jni_NativeTAP_00024MarketData_deregister
  (JNIEnv *, jobject);

/*
 * Class:     com_unown_tap_jni_NativeTAP_MarketData
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_unown_tap_jni_NativeTAP_00024MarketData_connect
  (JNIEnv *, jobject);

/*
 * Class:     com_unown_tap_jni_NativeTAP_MarketData
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_unown_tap_jni_NativeTAP_00024MarketData_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     com_unown_tap_jni_NativeTAP_MarketData
 * Method:    subscribe
 * Signature: (Lcom/unown/tap/jni/NativeTAP/MarketData/ContractInfo;)V
 */
JNIEXPORT void JNICALL Java_com_unown_tap_jni_NativeTAP_00024MarketData_subscribe
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_unown_tap_jni_NativeTAP_MarketData
 * Method:    unsubscribe
 * Signature: (Lcom/unown/tap/jni/NativeTAP/MarketData/ContractInfo;)V
 */
JNIEXPORT void JNICALL Java_com_unown_tap_jni_NativeTAP_00024MarketData_unsubscribe
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_unown_tap_jni_NativeTAP_MarketData_Configuration */

#ifndef _Included_com_unown_tap_jni_NativeTAP_MarketData_Configuration
#define _Included_com_unown_tap_jni_NativeTAP_MarketData_Configuration
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_unown_tap_jni_NativeTAP_MarketData_ContractInfo */

#ifndef _Included_com_unown_tap_jni_NativeTAP_MarketData_ContractInfo
#define _Included_com_unown_tap_jni_NativeTAP_MarketData_ContractInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_unown_tap_jni_NativeTAP_OrderEntry */

#ifndef _Included_com_unown_tap_jni_NativeTAP_OrderEntry
#define _Included_com_unown_tap_jni_NativeTAP_OrderEntry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_unown_tap_jni_NativeTAP_OrderEntry
 * Method:    register
 * Signature: (Lcom/unown/tap/jni/NativeCallback;Lcom/unown/tap/jni/NativeTAP/OrderEntry/Configuration;)V
 */
JNIEXPORT void JNICALL Java_com_unown_tap_jni_NativeTAP_00024OrderEntry_register
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_unown_tap_jni_NativeTAP_OrderEntry
 * Method:    deregister
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_unown_tap_jni_NativeTAP_00024OrderEntry_deregister
  (JNIEnv *, jobject);

/*
 * Class:     com_unown_tap_jni_NativeTAP_OrderEntry
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_unown_tap_jni_NativeTAP_00024OrderEntry_connect
  (JNIEnv *, jobject);

/*
 * Class:     com_unown_tap_jni_NativeTAP_OrderEntry
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_unown_tap_jni_NativeTAP_00024OrderEntry_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     com_unown_tap_jni_NativeTAP_OrderEntry
 * Method:    request
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_unown_tap_jni_NativeTAP_00024OrderEntry_request
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_unown_tap_jni_NativeTAP_OrderEntry_Configuration */

#ifndef _Included_com_unown_tap_jni_NativeTAP_OrderEntry_Configuration
#define _Included_com_unown_tap_jni_NativeTAP_OrderEntry_Configuration
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
