/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_unown_ctp_jni_NativeCTP */

#ifndef _Included_com_unown_ctp_jni_NativeCTP
#define _Included_com_unown_ctp_jni_NativeCTP
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_unown_ctp_jni_NativeCTP_MarketData */

#ifndef _Included_com_unown_ctp_jni_NativeCTP_MarketData
#define _Included_com_unown_ctp_jni_NativeCTP_MarketData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_unown_ctp_jni_NativeCTP_MarketData
 * Method:    register
 * Signature: (Lcom/unown/java/jni/NativeCallback;Lcom/unown/ctp/jni/NativeCTP/MarketData/Configuration;)V
 */
JNIEXPORT void JNICALL Java_com_unown_ctp_jni_NativeCTP_00024MarketData_register
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_unown_ctp_jni_NativeCTP_MarketData
 * Method:    deregister
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_unown_ctp_jni_NativeCTP_00024MarketData_deregister
  (JNIEnv *, jobject);

/*
 * Class:     com_unown_ctp_jni_NativeCTP_MarketData
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_unown_ctp_jni_NativeCTP_00024MarketData_connect
  (JNIEnv *, jobject);

/*
 * Class:     com_unown_ctp_jni_NativeCTP_MarketData
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_unown_ctp_jni_NativeCTP_00024MarketData_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     com_unown_ctp_jni_NativeCTP_MarketData
 * Method:    subscribe
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_unown_ctp_jni_NativeCTP_00024MarketData_subscribe
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_unown_ctp_jni_NativeCTP_MarketData
 * Method:    unsubscribe
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_unown_ctp_jni_NativeCTP_00024MarketData_unsubscribe
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_unown_ctp_jni_NativeCTP_MarketData_Configuration */

#ifndef _Included_com_unown_ctp_jni_NativeCTP_MarketData_Configuration
#define _Included_com_unown_ctp_jni_NativeCTP_MarketData_Configuration
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_unown_ctp_jni_NativeCTP_OrderEntry */

#ifndef _Included_com_unown_ctp_jni_NativeCTP_OrderEntry
#define _Included_com_unown_ctp_jni_NativeCTP_OrderEntry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_unown_ctp_jni_NativeCTP_OrderEntry
 * Method:    register
 * Signature: (Lcom/unown/java/jni/NativeCallback;Lcom/unown/ctp/jni/NativeCTP/OrderEntry/Configuration;)V
 */
JNIEXPORT void JNICALL Java_com_unown_ctp_jni_NativeCTP_00024OrderEntry_register
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_unown_ctp_jni_NativeCTP_OrderEntry
 * Method:    deregister
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_unown_ctp_jni_NativeCTP_00024OrderEntry_deregister
  (JNIEnv *, jobject);

/*
 * Class:     com_unown_ctp_jni_NativeCTP_OrderEntry
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_unown_ctp_jni_NativeCTP_00024OrderEntry_connect
  (JNIEnv *, jobject);

/*
 * Class:     com_unown_ctp_jni_NativeCTP_OrderEntry
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_unown_ctp_jni_NativeCTP_00024OrderEntry_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     com_unown_ctp_jni_NativeCTP_OrderEntry
 * Method:    request
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_unown_ctp_jni_NativeCTP_00024OrderEntry_request
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_unown_ctp_jni_NativeCTP_OrderEntry_Configuration */

#ifndef _Included_com_unown_ctp_jni_NativeCTP_OrderEntry_Configuration
#define _Included_com_unown_ctp_jni_NativeCTP_OrderEntry_Configuration
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
